### PR TITLE
Add Content-Security-Policy (CSP) #4

### LINKED ISSUE #4: add Content-Security-Policy (CSP)
… to prevent e.g. injected code.

This won't block all attacks, especially as the CSP is embedded in the HTML file itself, but better than nothing I'd say.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#examples_common_use_cases

### PR DESCRIPTION
**Pull request by ambujsahu81**
**What is the PR for?**

- Closes [#4](https://github.com/derhuerst/self-decrypting-html-page/issues/4) 
-  Adds Content-Security-Policy.
- Fixes small typo in readme.md

### CODE REVIEW

**Comment by ambujsahu81** [comment]
Hi @derhuerst :wave: 
Is this expected solution ? can you please review this PR :slightly_smiling_face:

**Comment by derhuerst** [comment]
> Is this expected solution ?

I guess! 😅 – I didn't know about `nonce` before, but it looks correct.

**Comment by derhuerst** [comment]
Would you like to be mentioned as a contributor in `package.json`? If you do, there are several [supported formats](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#people-fields-author-contributors). e.g. `ambujsahu81 <Ambuj.sahu1998@gmail.com>`.

**Comment by ambujsahu81** [comment]
> Would you like to be mentioned as a contributor in `package.json`? If you do, there are several [supported formats](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#people-fields-author-contributors). e.g. `ambujsahu81 <Ambuj.sahu1998@gmail.com>`.

Thanks for merging :slightly_smiling_face:. ok i will create pr for the same, adding me as contributor,

**Pull request merged**
